Adds journal_lines stream
hotgluexyz/tap-xero pull request #9
Opened 2024-02-06 13:46 UTC by vmesel

# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2024-02-06 14:33 UTC, hsyyid requested changes

2024-02-06 14:33 UTC, hsyyid commented on tap_xero/streams.py
> +            if "JournalLines" in rec and len(line_mdata) > 0:
This `len(line_mdata)` will fail if `line_mdata` is `None`

2024-02-06 14:33 UTC, hsyyid commented on tap_xero/streams.py
> +            line_mdata = [i for i in mdata if "JournalLines" in i.get("breadcrumb", [])]
So we're just checking if `JournalLines` exists as a field in the metadata? Or are we actually adding a new stream?

2024-02-06 14:38 UTC, vmesel commented on tap_xero/streams.py
> +            if "JournalLines" in rec and len(line_mdata) > 0:
Solving.

2024-02-06 14:38 UTC, vmesel commented on tap_xero/streams.py
> +            line_mdata = [i for i in mdata if "JournalLines" in i.get("breadcrumb", [])]
We are checking if JournalLines exist in the record and in the metadata.

2024-02-07 16:14 UTC, hsyyid approved these changes

2024-02-07 16:14 UTC, merged